version: '3'
services:
  api:
    image: node:16.19.0-alpine3.16
    restart: always
    volumes: 
      - ./:/app
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  mongo:
    image: mongo:5
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

